{
    'name': 'Woocommerce Integration Lite',
    "summary": "Odoo Woocommerce Connector, Odoo Woocommerce Integration",
    "category": "Sales",
    "version": "15.0.1.0.1",
    "author": "INKERP",
    "website": "http://www.inkerp.com",
    'depends': ["eg_ecommerce_base", "product"],
    'data': [
        'security/ir.model.access.csv',
        'wizards/product_template_instance.xml',
        'wizards/sale_order_wizard_view.xml',
        'wizards/import_from_ecom_provider_view.xml',
        'data/import_sale_order_cron.xml',
        'views/eg_ecom_instance_view.xml',
        'views/res_config_settings_view.xml',
        'views/sale_order_view.xml',
        'views/eg_product_template.xml',
        'views/eg_product_attribute.xml',
        'views/eg_product_category_view.xml',
        'views/eg_product_product_view.xml',
        'views/eg_res_partner_view.xml',
        'views/eg_sale_order_view.xml',
        'views/woo_tax_rate_view.xml',
        'views/eg_account_journal_view.xml',
        'views/woo_tax_class_view.xml',
        'views/woo_product_coupon_view.xml',
        'views/eg_attribute_value_view.xml',
    ],
    'installable': True,
    'images': ['static/description/banner.gif'],
    'license': "OPL-1",
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_hook',
    'uninstall_hook': "uninstall_hook",

}
